name: Build Teensy Remora Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install GCC ARM toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10-2020-q4-major'

      - name: Install mbed-cli
        run: pip install mbed-cli

      - name: Set Mbed Target
        run: mbed target TEENSY41

      - name: Set Mbed Toolchain
        run: mbed toolchain GCC_ARM

      - name: Clone working mbed-os
        run: |
          git clone https://github.com/ARMmbed/mbed-os.git
          cd mbed-os
          git checkout mbed-os-5.15.6
          cd ..

      - name: Install required Python packages
        run: pip install jinja2 jsonschema pyyaml pyelftools cryptography click cbor psutil intelhex

      - name: Patch elftools reference
        run: |
          sed -i 's/from elftools.common.py3compat import bytes2str/bytes2str = lambda x: x.decode()/' mbed-os/tools/flash_algo/__init__.py

      - name: Compile firmware
        run: |
          mbed compile --profile release -t GCC_ARM -m TEENSY41

      - name: Upload HEX
        uses: actions/upload-artifact@v4
        with:
          name: Remora-Teensy41-Firmware
          path: BUILD/TEENSY41/GCC_ARM/Teensy-Remora-SPI-Build.hex
